---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mouse
  labels:
    app: mouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mouse
  template:
    metadata:
      labels:
        app: mouse
    spec:
      containers:
      - name: mouse
        image: gcr.io/john-zqazd/mouse:latest  # Update this with your registry
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "mouse"
        - name: DB_USER
          value: "mouse"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mouse-secrets
              key: DB_PASSWORD
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: mouse-secrets
              key: OPENAI_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "4Gi"
            cpu: "2Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.1
        args:
        - "--structured-logs"
        - "--port=5432"
        - "john-zqazd:us-west1:agent-ops-dev"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"